### ISSUE TITLE
Add option for port mirroring

### ISSUE THREAD

**Issue by melkypie** [aristanetworks/ansible-avd#1412]
### Enhancement summary

Currently the only way to achieve port mirroring is by using the `eos_raw_cli` option in `eos_designs`, it would be nice if it had a dedicated option inside `connected_endpoints.adapters`

### Which component of AVD is impacted

eos_designs, eos_cli_config_gen

### Use case example

Port mirroring is useful for monitoring and network probes.

### Describe the solution you would like

Something similar to this :
```yaml
servers:
  server1:
    adapters:
      - switch_ports: [Ethernet1]
        server_ports: [eth0]
        switches: [switch1]
        sessions:
           - name: 1
             type: source
             direction: tx
```
that would grab the interface/s from the switch_ports or port_channel, if one is defined, and assign it with the specified session.
This would be generated in EOS as:
```
monitor session 1 source Ethernet1 tx
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by c-po** [comment]
We actually have the same issue on our side. Using `eos_cli` has the drawback that it can only be used once per switch - thus if you use it for other "switch specificas" you might override them when mirroring is used for 50% of the ports in a fabric.

**Comment by ccsnw** [comment]
@ClausHolbechArista can you assign this one to me? I've already started working on it some days ago, just need to finish the documentation part an upload.
Thanks!

**Comment by ClausHolbechArista** [comment]
Resolved by #1435

**Comment by melkypie** [comment]
#1435 only resolves the eos_cli_config_gen part of the issue. The eos_designs implementation is still missing.

**Comment by ccsnw** [comment]
True! I'd also like to take a look at the eos_designs part once  I have some spare time. It'd be a good opportunity to dive into it

**Comment by ClausHolbechArista** [comment]
> #1435 only resolves the eos_cli_config_gen part of the issue. The eos_designs implementation is still missing.

Sorry I missed that. Reopened and I hope @ccsnw will take it on. Ping me if you need help.

**Comment by ccsnw** [comment]
will do! just give me some time, have a couple of other things to finish first
