### ISSUE TITLE
Issue occured while using artista avd version v4.4.0

### ISSUE THREAD

**Issue by duddis1** [aristanetworks/ansible-avd#3892]
HI Team,

We are getting below error while generating intended config using arista avd version v4.4.0.

This has worked till last week, do you know any validation has been added on top of this image. Below is the error message.

TASK [arista.avd.eos_designs : Generate fabric documentation] *****************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: module 'md_toc' has no attribute 'build_toc'
fatal: [LON-IX-SW -> localhost]: FAILED! => {"changed": false}

NO MORE HOSTS LEFT ************************************************************************************************************************************************************************************************
PLAY RECAP ********************************************************************************************************************************************************************************************************
LON-IX-SW                  : ok=16   changed=11   unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
MAN-IX-SW                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

**Comment by duddis1** [comment]
Below is the error message while running in debug mode:

TASK [arista.avd.eos_designs : Generate fabric documentation] *****************************************************************************************************************************************************
task path: /home/avd/.ansible/collections/ansible_collections/arista/avd/roles/eos_designs/tasks/main.yml:62
The full traceback is:
Traceback (most recent call last):
  File "/home/avd/.local/share/virtualenvs/netbox_extract-zMJz_RXI/lib/python3.9/site-packages/ansible/executor/task_executor.py", line 505, in _execute
    self._task.post_validate(templar=templar)
  File "/home/avd/.local/share/virtualenvs/netbox_extract-zMJz_RXI/lib/python3.9/site-packages/ansible/playbook/task.py", line 291, in post_validate
    super(Task, self).post_validate(templar)
  File "/home/avd/.local/share/virtualenvs/netbox_extract-zMJz_RXI/lib/python3.9/site-packages/ansible/playbook/base.py", line 541, in post_validate
    value = method(attribute, getattr(self, name), templar)
  File "/home/avd/.local/share/virtualenvs/netbox_extract-zMJz_RXI/lib/python3.9/site-packages/ansible/playbook/task.py", line 299, in _post_validate_args
    args = templar.template(value)
  File "/home/avd/.local/share/virtualenvs/netbox_extract-zMJz_RXI/lib/python3.9/site-packages/ansible/template/__init__.py", line 764, in template
    d[k] = self.template(
  File "/home/avd/.local/share/virtualenvs/netbox_extract-zMJz_RXI/lib/python3.9/site-packages/ansible/template/__init__.py", line 738, in template
    result = self.do_template(
  File "/home/avd/.local/share/virtualenvs/netbox_extract-zMJz_RXI/lib/python3.9/site-packages/ansible/template/__init__.py", line 1001, in do_template
    res = myenv.concat(rf)
  File "/home/avd/.local/share/virtualenvs/netbox_extract-zMJz_RXI/lib/python3.9/site-packages/ansible/template/native_helpers.py", line 43, in ansible_eval_concat
    head = list(islice(nodes, 2))
  File "<template>", line 18, in root
  File "/home/avd/.local/share/virtualenvs/netbox_extract-zMJz_RXI/lib/python3.9/site-packages/ansible/template/__init__.py", line 262, in wrapper
    ret = func(*args, **kwargs)
  File "/home/avd/.ansible/collections/ansible_collections/arista/avd/plugins/filter/add_md_toc.py", line 121, in add_md_toc
    toc = md_toc.build_toc("-", keep_header_levels=toc_levels, skip_lines=skip_lines).rstrip()
AttributeError: module 'md_toc' has no attribute 'build_toc'
fatal: [MAN-IX-SW -> localhost]: FAILED! => {
    "changed": false
}

NO MORE HOSTS LEFT ************************************************************************************************************************************************************************************************

PLAY RECAP ********************************************************************************************************************************************************************************************************
LON-IX-SW                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
MAN-IX-SW                  : ok=16   changed=6    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by gmuloc** [comment]
Hi @duddis1 

You are probably hitting the `md_toc` new version issue.
We have fixed this in newer release by handling the different major versions in our code for now: https://github.com/aristanetworks/avd/pull/3837

For your issue you can either:

1. Upgrade to AVD 4.7.1
2. Cap `md_toc` by doing `pip install --upgrade "md_toc<9"`


Please feel free to re-open if this does not solve your issue

**Comment by duddis1** [comment]
> Hi @duddis1
> 
> You are probably hitting the `md_toc` new version issue. We have fixed this in newer release by handling the different major versions in our code for now: #3837
> 
> For your issue you can either:
> 
> 1. Upgrade to AVD 4.7.1
> 2. Cap `md_toc` by doing `pip install --upgrade "md_toc<9"`
> 
> Please feel free to re-open if this does not solve your issue

I tried below two option, but still seeing the error, can you please provide exact md_toc version which we can use?
pip install --upgrade "md_toc<9"
pip install --upgrade "md_toc=9.0.0"

**Comment by gmuloc** [comment]
The error you shared is exactly the traceback we were getting so I do believe it should work

So in theory you should be able to make it work with:
* AVD 4.4
* `pip install --upgrade "md_toc<9"`

Right now it is difficult to assist you further without some extra logs.

Can you please share:
1/ how you are using AVD (container, python system install, virtual env)
2/ share `pip freeze` output from within the correct virtual environment (or pip3 freeze)
3/ share the JSON output from your playbook step called `Verify Requirement`, you just need to run the playbook with verbose mode `-v` to get it.
