### ISSUE TITLE
p2p-vrfs generate MTU configuration on subinterfaces causing unsupported command

### ISSUE THREAD

**Issue by CyrielRct** [aristanetworks/ansible-avd#5585]
### Issue Summary

When using uplink_type: p2p-vrfs, subinterfaces are created per VRF, which is expected behavior. However, the MTU value is also applied to those subinterfaces, and on certain hardware platforms, this leads to the following error:

Unavailable command (not supported on this hardware platform)

### Which components of AVD are impacted

eos_designs

### AVD version

5.4.0

### How do you run AVD ?

AVD container

### Steps to reproduce

```shell
AVD topology configuration:


l3spine:
  defaults:
    platform: default
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    loopback_ipv4_pool: 10.10.10.0/24
    virtual_router_mac_address: 00:1c:73:00:dc:05
    bgp_as: 4200199001
  nodes:
    - name: EDGE
      id: 111
      inband_mgmt_ip: 10.11.12.13/24
      inband_mgmt_interface: Vlan10
      inband_mgmt_vlan: 10
      uplink_interfaces: [ Ethernet48 ]
      uplink_switches: [ CORE ]
      uplink_switch_interfaces: [ Ethernet1 ]
      uplink_ipv4_pool: 10.199.255.0/24
      uplink_type: p2p-vrfs


interface Ethernet48.10
   encapsulation dot1q 10
   mtu 9214  ! <- This line causes the error on some platforms
   vrf RED
   ip address 10.199.255.1/31
```

### workaround

```shell
custom_structured_configuration_ethernet_interfaces:
  - name: Ethernet1.253
    mtu: null
```

### Contributing Guide

- [x] I agree to follow this project Code of Conduct

**Comment by gmuloc** [comment]
Fixed in https://github.com/aristanetworks/avd/pull/5456 that will be in AVD 5.5

**Comment by CyrielRct** [comment]
Hi @gmuloc 
I did upgraded AVD to 5.5.1 and I'm still having the issue. 

```
interface Ethernet54
   no shutdown
   mtu 9214
   no switchport
   ip address x.x.x.x/x
   pim ipv4 sparse-mode
   ptp enable
   ptp announce interval 0
   ptp announce timeout 3
   ptp delay-req interval -3
   ptp sync-message interval -3
   ptp transport ipv4
!
interface Ethernet54.252
   no shutdown
   mtu 9214. <----------------------- 
   encapsulation dot1q vlan 252
   vrf BLUE
   ip address x.x.x.y/x
```

```
uplink_type: p2p-vrfs

platform_settings:
  - feature_support:
      subinterface_mtu: false
    platforms:
      - default

```

**Comment by ClausHolbechArista** [comment]
We added a knob under `custom_platform_settings` where you can say if the platform supports per-subinterface MTU or not. We will not update the defaults until AVD 6.0, so for now you have to define your own `custom_platform_settings`. I would suggest to copy the relevant default from `platform_settings` and modify that.

The default can be found by going here: https://avd.arista.com/5.5/ansible_collections/arista/avd/roles/eos_designs/docs/input-variables.html#platform-settings

Select the YAML tab, then click the (+) here: 

<img width="286" height="98" alt="Image" src="https://github.com/user-attachments/assets/42e25493-80f0-43fb-bb3a-c99f3f2292dc" />

**Comment by dgonzalez-arista** [comment]
As dicussed with @gmuloc in PS we have added the following custom platform settings for veos:
```
custom_platform_settings:
  - platforms:
      - vEOS-lab
    default_interface_mtu: 1500
    p2p_uplinks_mtu: 1500
    digital_twin:
      act_node_type: "veos"
    feature_support:
      bgp_update_wait_for_convergence: false
      bgp_update_wait_install: false
      interface_storm_control: false
      queue_monitor_length_notify: false
      evpn_gateway_all_active_multihoming: true
      queue_monitor: false
      subinterface_mtu: false
```

Only not present in the platforms defaults today should be "subinterface_mtu" and also "queue_monitor".
